import base64
import hashlib
import hmac
import json

from django.utils import timezone
from django.shortcuts import redirect, render
from django.views.decorators.http import require_GET

from cart.models import Cart
from order.models import Order
from payment.models import Payment

# eSewa merchant credentials (must match the values used when initiating payment)
ESEWA_SECRET_KEY = '8gBm/:&EnhH.1/q'
ESEWA_PRODUCT_CODE = 'EPAYTEST'


def generate_signature(total_amount, transaction_uuid, product_code,
                        secret_key=ESEWA_SECRET_KEY):
    """Generate the eSewa HMAC-SHA256 signature.

    The response signature is generated by eSewa over the exact same fields and
    in the exact same way as the request signature, so we reuse this function
    to verify the integrity of the callback payload.
    """
    message = f"total_amount={total_amount},transaction_uuid={transaction_uuid},product_code={product_code}"
    digest = hmac.new(secret_key.encode(), message.encode(), hashlib.sha256).digest()
    return base64.b64encode(digest).decode()


def _decode_esewa_data(encoded_data):
    """Decode the base64 `data` query param into a dict. Returns (data, error)."""
    if not encoded_data:
        return None, 'Missing payment data.'
    try:
        decoded = base64.b64decode(encoded_data).decode('utf-8')
        data = json.loads(decoded)
    except Exception:
        return None, 'Failed to decode payment response.'
    return data, None


@require_GET
def esewa_success(request):
    data, error = _decode_esewa_data(request.GET.get('data'))

    if error:
        messages_error(request, error)
        return redirect('checkout')

    status = data.get('status')
    if status != 'COMPLETE':
        messages_error(request, 'Payment was not completed.')
        return redirect('esewa_failure')

    # 2. Identify the order we created (we sent order.id as transaction_uuid).
    transaction_uuid = data.get('transaction_uuid')
    try:
        order = Order.objects.get(id=transaction_uuid)
    except (Order.DoesNotExist, ValueError):
        messages_error(request, 'Order not found for this transaction.')
        return redirect('checkout')

    # 3. Persist the successful payment.
    order.transaction_uuid = data.get('transaction_code')
    order.payment_status = 'paid'
    order.status = 'confirmed'
    order.save()

    Payment.objects.update_or_create(
        order=order,
        defaults={
            'provider': 'esewa',
            'provider_ref': data.get('transaction_code') or '',
            'status': 'completed',
            'amount': order.total_amount,
            'paid_at': timezone.now(),
        },
    )

    # 4. Clear the cart and pending session state.
    cart = Cart.objects.filter(user=order.user).first()
    if cart:
        cart.items.all().delete()
    request.session.pop('pending_order_id', None)
    request.session['esewa_response'] = data

    messages_success(request, 'Payment successful. Your order is confirmed.')
    return render(request, 'payment/payment_success.html', {
        'order': order,
        'data': data,
    })


@require_GET
def esewa_failure(request):
    data, error = _decode_esewa_data(request.GET.get('data'))
    if error:
        data = {}

    # Mark the order as failed if we can identify it.
    transaction_uuid = data.get('transaction_uuid') or request.session.get('pending_order_id')
    if transaction_uuid:
        try:
            order = Order.objects.get(id=transaction_uuid)
            order.payment_status = 'failed'
            order.save()
            Payment.objects.update_or_create(
                order=order,
                defaults={
                    'provider': 'esewa',
                    'status': 'failed',
                    'amount': order.total_amount,
                },
            )
        except (Order.DoesNotExist, ValueError):
            pass

    request.session.pop('pending_order_id', None)

    return render(request, 'payment/payment_failure.html', {
        'data': data,
        'reason': data.get('status') or data.get('errorMessage') or 'Payment failed or was cancelled.',
    })


def messages_error(request, text):
    from django.contrib import messages
    messages.error(request, text)


def messages_success(request, text):
    from django.contrib import messages
    messages.success(request, text)
