# Generated by Django 6.0.5 on 2026-05-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_uuid',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
